### ISSUE TITLE
Linux and first steps

### ISSUE THREAD

**Issue by AndreasS2501** [glenbraun/JsonPi#1]
Hi Glenn,

this is Andreas we meet at the recent RChain conference.
Using MonoDevelop (Linux .NET IDE)
http://www.monodevelop.com/download/#fndtn-download-lin

and the .NET SDK Linux Version, I was able to import your project and start the JsonPi part, I guess. I then got a Interpreter Shell (Run>) 

I tried then to execute this(was this a mistake?)
  world<hello>; | world(message);
Run>   x<a,b,c>

Unhandled Exception: System.Exception: parse error
   at Microsoft.FSharp.Text.Parsing.Implementation.popStackUntilErrorShifted@278[tok,a](Tables`1 tables, LexBuffer`1 lexbuf, Stack`1 stateStack, Stack`1 valueStack, AssocTable actionTable, FSharpOption`1 tokenOpt) in /home/ascheinert/JsonPi/FsLexYacc.Runtime/Parsing.fs:line 283
   at Microsoft.FSharp.Text.Parsing.Implementation.interpret[tok,a](Tables`1 tables, FSharpFunc`2 lexer, LexBuffer`1 lexbuf, Int32 initialState) in /home/ascheinert/JsonPi/FsLexYacc.Runtime/Parsing.fs:line 485
   at JsonPiRepl.main(String[] argv) in /home/ascheinert/JsonPi/JsonPiREPL/Program.fs:line 15
bash: Zeile 1: 16265 Abgebrochen             (Speicherabzug geschrieben) /usr/share/dotnet/dotnet "/home/ascheinert/JsonPi/JsonPiREPL/bin/Release/netcoreapp2.0/JsonPiREPL.dll"

Press any key to continue..

=====>
What kind of commands does the REPL handle currently?
Anyway I just wanted to say that Mono and the .NET SDK for Linux are a good start to get started on Linux. I'm really looking forward to use the REPL in the coming sessions.

regards Andreas

**Comment by glenbraun** [comment]
Thanks for giving it a try. Good to know it's runnable on Linux.

world; | world(message); is not quite the right syntax.

world\<hello\>; | world(message);
should work.

Aslo,  x\<a,b,c\> has a syntax error too, needs to be 
x\<a,b,c\>;
The x<a,b,c> is a prefix, but it must be followed by a process. Adding a ; ends the statement with the inactive process.

I'm surprised that an unhandled exception occurred, since I have code which does handle the exception. When running in windows I get a line of text that says "Execution: parse error", but then returns to a Run> prompt.

I'll have to try to reproduce on Linux/Mono to see about the exception handling issue.

In the source code, there is a folder called Test. In the Program.fs file you will see some test expressions which are known to work. Some of Milner's examples are in there too.

Cheers, Andreas. Good hearing from you.

**Comment by glenbraun** [comment]
I just noticed that GitHub markdown is eating the '\<' characters. So, maybe you were entering syntax correctly. Not sure.

**Comment by JoshOrndorff** [comment]
I confirm that the syntax @glenbraun listed above executes without error on linux.

@AndreasS2501 Did that solve the issue for you?

**Comment by glenbraun** [comment]
(I'm pretty sure this issue is caused by the same root cause as issue 3.)

I was able to reproduce the issue when running in Linux. I'm not sure the reason but the command parser I was using failed on Linux vs. in Windows. I replaced the command processor with something much simpler and it seems to work fine in both Windows and Linux now.
